version: "3"

services:

  app:
    image: slack-groupme-bridge
    build:
      context: ./app-docker

  nginx:
    image: slack-groupme-nginx
    build:
      context: ./nginx-docker
    ports:
      - 5000:80
    links:
      - app